services:
  - type: web
    name: coolcache-backend
    env: node
    repo: hadeedhussainmemon/CoolCache
    branch: main
    buildCommand: "npm install --prefix Backend"
    startCommand: "npm start --prefix Backend"
    healthCheckPath: "/api/health"
    plan: free
